data:
  examples: "valid_examples_listseq.csv"
  labels: "valid_labels_listseq.csv"
  scale_labels: true


training:
  epochs: 1000
  batch_size: 16
  lr: 0.001
  seed: 42


model:
  type: "resnet_mlp"
  hidden_dims: [8192, 4096,2048, 1024,512, 256, 64, 16]
  dropout: 0.3
  use_batchnorm: true


paths:
  save_dir: "outputs"


print:
  verbose: true